---
galaxy_info:
  author:
  description: Instalar Elastic MetricBean para reporte de metricas de ElasticSearch.
  license:
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
  - monitoring
  - system
dependencies: []
