---
- name: Metric Beat| ensure directories
  file:
    path: /etc/metricbeat
    state: directory
  become: yes

- include: debian.yaml
  when: ansible_os_family == 'Debian'

- include: redhat.yaml
  when: ansible_os_family == 'RedHat'

- name: SO fammily
  debug:
    msg: "OS Family {{ansible_os_family}}" 

- name: Metric Beat| create metricbeat.yml
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
  become: yes
  notify:
  - restart metricbeat
  tags:
  - update_metricbeat_config

- name: Metric Beat| copy ca certificate if required
  copy:
    content: "{{ metricbeat_ca_cert }}"
    dest: "{{ metricbeat_ca_path }}"
    owner: root
    group: root
    mode: 0400
  when: metricbeat_ca_cert != None

- name: Metric Beat| flush handlers to prevent start then restart
  meta: flush_handlers
  tags:
  - update_metricbeat_config

- name: Metric Beat| start and enable metricbeat
  service:
    name: metricbeat
    state: started
    enabled: true
  tags:
  - update_metricbeat_config
