---
#- name: Elastic| add rpm key for elastic.co
#  rpm_key:
#    key: "{{ metricbeat_gpg_url }}"
#
#- name: Beats| create beats yum repo
#  yumrepo:
#    name: beats
#    baseurl: "{{ metricbeat_repo_url }}"
#    enabled: yes
#    gpgcheck: yes
#    gpgkey: "{{ metricbeat_gpg_url }}"

#- name: Beat| install metricbeat
#  yum:
#    name: "metricbeat-{{ metricbeat_version }}"
#    state: present
#  notify:
# - restart metricbeat
