metricbeat_config:
  fields:
    env: "{{ env | default('dev') }}"
  metricbeat.modules:
  - module: system
    metricsets:
    - cpu
    - load
    - core
    - diskio
    - filesystem
    - fsstat
    - memory
    - network
    - process
    - socket
    enabled: true
    period: 60s
    processes: ['.*']
  output.elasticsearch:
    enabled: true
    hosts: ["{{ elasticsearch_proxy_url }}"]
    username: "{{ es_filebeat_user }}"
    password: "{{ es_filebeat_password }}"
    index: "metricbeat-{{env}}-%{+yyyy.MM.dd}"
  logging:
    to_syslog: false
    to_files: true
    level: error
    files:
    - path: /var/log/metricbeat
    - name: metricbeat.log
    - keepfiles: 5
    - rotateeverybytes: 10485760 # = 10MB


# Parametros para establecer certificado
# metricbeat_ca_cert: "{{ lookup('file', '/path/to/ca.crt') }}"
metricbeat_ca_cert: null
# Donde colocar el certificado si se especifica parametro previo
metricbeat_ca_path: /etc/metricbeat/ca.crt

metricbeat_gpg_url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
# Para SO de la familia Debian
metricbeat_apt_repo_v1: "deb https://packages.elastic.co/beats/apt stable main"
metricbeat_apt_repo_v5: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
metricbeat_apt_repo: "{{ metricbeat_version|version_compare('5', '<')|ternary(metricbeat_apt_repo_v1, metricbeat_apt_repo_v5) }}"
# Para SO de la familia RedHat
metricbeat_repo_url_v1: https://packages.elastic.co/beats/yum/el/$basearch
metricbeat_repo_url_v5: https://artifacts.elastic.co/packages/5.x/yum
metricbeat_repo_url: "{{ metricbeat_version|version_compare('5', '<')|ternary(metricbeat_repo_url_v1, metricbeat_repo_url_v5) }}"

elasticsearch_proxy_url: http://127.0.0.1:9200
es_filebeat_user: elastic
es_filebeat_password: welcome1
